<script setup lang="ts">
import { FolderTree, ListFilter, Pencil, Trash2 } from '@lucide/vue'
import UiBadge from '../../../components/ui/UiBadge.vue'
import UiButton from '../../../components/ui/UiButton.vue'
import UiCard from '../../../components/ui/UiCard.vue'
import UiEmptyState from '../../../components/ui/UiEmptyState.vue'
import UiLoadingState from '../../../components/ui/UiLoadingState.vue'
import type { Category } from '../types/category.types'
defineProps<{ categories: Category[]; loading: boolean; canManage: boolean; categoryName: (id: number | null | undefined) => string | null }>()
const emit = defineEmits<{ details: [category: Category]; edit: [category: Category]; configure: [category: Category]; remove: [category: Category] }>()
</script>
<template><UiCard class="overflow-hidden"><UiLoadingState v-if="loading" label="Загрузка категорий…" /><div v-else-if="categories.length" class="divide-y divide-gray-100"><article v-for="category in categories" :key="category.id" class="flex flex-wrap items-start gap-3 p-4 sm:flex-nowrap sm:items-center sm:gap-4"><span class="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-primary-50 text-primary-600"><FolderTree :size="20" /></span><div class="min-w-0 flex-[1_1_calc(100%-52px)] sm:flex-1"><div class="flex flex-wrap items-center gap-2"><UiButton variant="ghost" size="sm" class="!-ml-3 !h-auto !min-h-0 !p-1 !text-left !text-sm" @click="emit('details', category)">{{ category.name }}</UiButton><UiBadge :tone="category.is_active ? 'success' : 'neutral'">{{ category.is_active ? 'Активна' : 'Скрыта' }}</UiBadge><UiBadge v-if="category.is_parent" tone="primary">Родительская</UiBadge></div><p class="mt-1 break-words text-sm text-gray-500">/{{ category.slug }} · Порядок: {{ category.sort_order }}</p><p v-if="category.parent_id" class="mt-1 text-xs text-gray-500">Родитель: {{ categoryName(category.parent_id) }}</p><p v-if="category.is_parent" class="mt-1 text-xs text-primary-600">Подкатегорий: {{ category.children?.length ?? 0 }}</p></div><div v-if="canManage" class="ml-[52px] flex gap-1 sm:ml-0"><UiButton variant="ghost" size="sm" :aria-label="`Настроить характеристики категории ${category.name}`" @click="emit('configure', category)"><ListFilter :size="17" /></UiButton><UiButton variant="ghost" size="sm" :aria-label="`Редактировать категорию ${category.name}`" @click="emit('edit', category)"><Pencil :size="17" /></UiButton><UiButton variant="ghost" size="sm" :aria-label="`Удалить категорию ${category.name}`" @click="emit('remove', category)"><Trash2 :size="17" /></UiButton></div></article></div><UiEmptyState v-else label="Категорий пока нет." /></UiCard></template>
