<script setup lang="ts">
import { X } from '@lucide/vue'
import UiBadge from '../../../components/ui/UiBadge.vue'
import UiButton from '../../../components/ui/UiButton.vue'
import UiDialog from '../../../components/ui/UiDialog.vue'
import type { Attribute } from '../../attributes/types/attribute.types'
import type { AttributeGroup } from '../../attribute-groups/types/attributeGroup.types'
import type { Category } from '../types/category.types'
const props = defineProps<{ category: Category | null; loading: boolean; attributes: Attribute[]; groups: AttributeGroup[]; categoryName: (id: number | null | undefined) => string | null }>()
const emit = defineEmits<{ close: [] }>()
const filterAttributes = () => props.attributes.filter(attribute => attribute.is_filterable)
</script>
<template><UiDialog :open="Boolean(category)" labelledby="category-details-title" panel-class="w-full max-w-2xl overflow-y-auto rounded-xl bg-white p-6 shadow-xl" @close="emit('close')"><template v-if="category"><div class="flex items-start justify-between gap-4"><div><p class="text-sm font-medium text-gray-500">Категория</p><h2 id="category-details-title" class="mt-1 text-xl font-bold text-gray-900">{{ category.name }}</h2></div><UiButton type="button" variant="ghost" size="sm" aria-label="Закрыть" @click="emit('close')"><X :size="20" /></UiButton></div><p v-if="loading" class="mt-6 py-8 text-center text-sm text-gray-500" role="status">Загрузка сведений о категории…</p><template v-else><dl class="mt-6 grid gap-4 rounded-xl border border-gray-200 p-4 text-sm sm:grid-cols-2"><div><dt class="text-gray-500">Slug</dt><dd class="mt-1 break-words font-medium text-gray-800">/{{ category.slug }}</dd></div><div><dt class="text-gray-500">Статус</dt><dd class="mt-1"><UiBadge :tone="category.is_active ? 'success' : 'neutral'">{{ category.is_active ? 'Активна' : 'Скрыта' }}</UiBadge></dd></div><div><dt class="text-gray-500">Родительская категория</dt><dd class="mt-1 font-medium text-gray-800">{{ categoryName(category.parent_id) ?? 'Нет' }}</dd></div><div><dt class="text-gray-500">Порядок сортировки</dt><dd class="mt-1 font-medium text-gray-800">{{ category.sort_order }}</dd></div><div class="sm:col-span-2"><dt class="text-gray-500">Описание</dt><dd class="mt-1 whitespace-pre-wrap text-gray-800">{{ category.description || 'Не указано' }}</dd></div></dl><section class="mt-5"><h3 class="font-semibold text-gray-900">Применённые группы</h3><div v-if="groups.length" class="mt-2 flex flex-wrap gap-2"><UiBadge v-for="group in groups" :key="group.id" tone="primary">{{ group.name }}</UiBadge></div><p v-else class="mt-2 text-sm text-gray-500">Группы не назначены.</p></section><section class="mt-5"><h3 class="font-semibold text-gray-900">Фильтры категории</h3><div v-if="filterAttributes().length" class="mt-2 flex flex-wrap gap-2"><UiBadge v-for="attribute in filterAttributes()" :key="attribute.id" tone="success">{{ attribute.name }}<template v-if="attribute.unit"> ({{ attribute.unit }})</template></UiBadge></div><p v-else class="mt-2 text-sm text-gray-500">Характеристики для фильтрации не назначены.</p></section><section class="mt-5"><h3 class="font-semibold text-gray-900">Все назначенные характеристики</h3><div v-if="attributes.length" class="mt-2 flex flex-wrap gap-2"><UiBadge v-for="attribute in attributes" :key="attribute.id" tone="neutral">{{ attribute.name }}<template v-if="attribute.unit"> ({{ attribute.unit }})</template><template v-if="attribute.is_required"> · обязательная</template></UiBadge></div><p v-else class="mt-2 text-sm text-gray-500">Не назначены.</p></section></template></template></UiDialog></template>
