import { apiFetch, requestCsrfCookie } from '../../../services/auth'
import { loadAllPages, withPage, type PageRequest, type PaginatedResponse } from '../../../services/pagination'
import type { Attribute, AttributePayload } from '../types/attribute.types'
export type { Attribute, AttributeOption, AttributePayload, AttributeType } from '../types/attribute.types'
async function fail(response: Response): Promise<never> { const body = (await response.json().catch(() => ({}))) as { error?: { message?: string; details?: Record<string, string[]> } }; throw new Error(Object.values(body.error?.details ?? {}).flat()[0] ?? body.error?.message ?? 'Не удалось выполнить запрос.') }
export async function getAttributes(request: PageRequest = {}): Promise<PaginatedResponse<Attribute>> { const query = new URLSearchParams(); withPage(query, request); const response = await apiFetch(`/admin/attributes${query.size ? `?${query}` : ''}`); if (!response.ok) return fail(response); return (await response.json()) as PaginatedResponse<Attribute> }
export async function getAllAttributes(): Promise<Attribute[]> { return loadAllPages(getAttributes) }
export async function saveAttribute(id: number | null, payload: AttributePayload): Promise<Attribute> { await requestCsrfCookie(); const body: Partial<AttributePayload> = { ...payload }; if (!['select', 'multiselect'].includes(payload.type)) delete body.options; const response = await apiFetch(id === null ? '/admin/attributes' : `/admin/attributes/${id}`, { method: id === null ? 'POST' : 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (!response.ok) return fail(response); return ((await response.json()) as { data: Attribute }).data }
export async function deleteAttribute(id: number): Promise<void> { await requestCsrfCookie(); const response = await apiFetch(`/admin/attributes/${id}`, { method: 'DELETE' }); if (!response.ok) return fail(response) }
