<script setup lang="ts">
import { ArrowDown, ArrowUp, ArrowUpDown, Copy, Download, EyeOff, Package, Pencil, Plus, Save, Upload, X } from '@lucide/vue'
import UiDialog from '../../../components/ui/UiDialog.vue'
import UiInput from '../../../components/ui/UiInput.vue'
import UiRadio from '../../../components/ui/UiRadio.vue'
import UiSelect from '../../../components/ui/UiSelect.vue'
import UiLoadingState from '../../../components/ui/UiLoadingState.vue'
import UiPagination from '../../../components/ui/UiPagination.vue'
import ProductImportDialog from './ProductImportDialog.vue'
import ProductPriceStatusImportDialog from './ProductPriceStatusImportDialog.vue'
import ProductGroupImportDialog from './ProductGroupImportDialog.vue'
import EditorSteps from './ProductEditorSteps.vue'
import ProductMainSection from './ProductMainSection.vue'
import ProductAttributesSection from './ProductAttributesSection.vue'
import ProductImagesSection from './ProductImagesSection.vue'
import ProductVariantsSection from './ProductVariantsSection.vue'
import ProductRelationsSection from './ProductRelationsSection.vue'
import ProductReviewSection from './ProductReviewSection.vue'
import { provideProductEditorContext } from '../composables/useProductEditorContext'
import { useProductEditor } from '../composables/useProductEditor'

const editor = useProductEditor()
provideProductEditorContext(editor)
const { products, pagination, error, loading, opened, saving, editing, deleting, activeStep, steps, success, confirmError, filterResultStatus, exportStatus, exporting, importOpened, priceStatusImportOpened, groupImportOpened, productCountUnavailable, filters, sort, direction, form, selectedGroupId, groupDeleting, imageDeleting, canManage, canManageImports, sortStatus, activityOptions, saleOptions, filterCategoryOptions, filterBrandOptions, hasActiveFilters, productCountLabel, ariaSort, formatDate, isProductNameTruncated, productNamePreview, load, resetFilters, changeSort, exportFilteredProducts, enabled, open, cloneProduct, close, removeProduct, removeImage, ungroup, publish, hideProduct } = editor
type Step = typeof activeStep.value
</script>
<template>
<section class="mx-auto" :aria-busy="loading"><div class="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-medium text-gray-500">Каталог</p><h1 class="mt-1 text-2xl font-bold text-gray-900 sm:text-3xl">Товары</h1></div><div class="flex flex-wrap gap-2"><button v-if="canManageImports" type="button" class="inline-flex items-center justify-center gap-2 rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm font-semibold text-gray-700 transition hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:ring-offset-2 disabled:cursor-wait disabled:opacity-60" @click="importOpened = true"><Upload :size="18" aria-hidden="true"/>Загрузить массово</button><button v-if="canManageImports" type="button" class="inline-flex items-center justify-center gap-2 rounded-lg border border-primary-200 bg-primary-50 px-4 py-2.5 text-sm font-semibold text-primary-700 transition hover:bg-primary-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:ring-offset-2" @click="priceStatusImportOpened = true"><Upload :size="18" aria-hidden="true"/>Цены и статусы</button><button v-if="canManageImports && canManage" type="button" class="inline-flex items-center justify-center gap-2 rounded-lg border border-primary-200 bg-primary-50 px-4 py-2.5 text-sm font-semibold text-primary-700 transition hover:bg-primary-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:ring-offset-2" @click="groupImportOpened = true"><Upload :size="18" aria-hidden="true"/>Группы вариантов</button><button v-if="canManageImports" type="button" class="inline-flex items-center justify-center gap-2 rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm font-semibold text-gray-700 transition hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:ring-offset-2 disabled:cursor-wait disabled:opacity-60" :disabled="exporting" :aria-busy="exporting" @click="exportFilteredProducts"><Download :size="18" aria-hidden="true"/>{{exporting?'Экспорт…':'Скачать Excel'}}</button><button v-if="canManage" class="inline-flex items-center justify-center gap-2 rounded-lg bg-primary-500 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-primary-600 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:ring-offset-2" @click="open()"><Plus :size="18" aria-hidden="true"/>Добавить товар</button></div></div>
<p v-if="error&&!opened" class="mb-4 rounded-lg border border-error-200 bg-error-50 px-4 py-3 text-sm text-error-500" role="alert">{{error}}</p>
<p v-if="exportStatus" class="mb-4 rounded-lg border border-success-200 bg-success-50 px-4 py-3 text-sm text-success-700" role="status">{{exportStatus}}</p>
<ProductImportDialog :open="importOpened" @close="importOpened = false" @completed="load(1)" />
<ProductPriceStatusImportDialog :open="priceStatusImportOpened" @close="priceStatusImportOpened = false" @completed="load(1)" />
<ProductGroupImportDialog :open="groupImportOpened" @close="groupImportOpened = false" @completed="load(1)" />
<form class="rounded-xl border border-gray-200 bg-white p-5 shadow-card" role="search" @submit.prevent><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><label class="text-sm font-medium text-gray-700 xl:col-span-2">Поиск<UiInput v-model="filters.search" class="mt-1.5" searchable placeholder="Название, SKU, артикул"/></label><label class="text-sm font-medium text-gray-700">Категория<UiSelect v-model="filters.category_id" class="mt-1.5" :options="filterCategoryOptions" accessible-name="Категория" search-placeholder="Начните вводить название категории" searchable/></label><label class="text-sm font-medium text-gray-700">Бренд<UiSelect v-model="filters.brand_id" class="mt-1.5" :options="filterBrandOptions" accessible-name="Бренд" search-placeholder="Начните вводить название бренда" searchable/></label></div><div class="mt-5 grid gap-4 lg:grid-cols-2"><fieldset><legend class="text-sm font-semibold text-gray-700">Активность</legend><div class="mt-2 grid gap-2 sm:grid-cols-3"><UiRadio v-for="option in activityOptions" :key="option.value" v-model="filters.is_active" class="focus-within:outline-none focus-within:ring-2 focus-within:ring-primary-500 focus-within:ring-offset-2" :value="option.value" name="product-activity-filter">{{option.label}}</UiRadio></div></fieldset><fieldset><legend class="text-sm font-semibold text-gray-700">Распродажа</legend><div class="mt-2 grid gap-2 sm:grid-cols-3"><UiRadio v-for="option in saleOptions" :key="option.value" v-model="filters.is_on_sale" class="focus-within:outline-none focus-within:ring-2 focus-within:ring-primary-500 focus-within:ring-offset-2" :value="option.value" name="product-sale-filter">{{option.label}}</UiRadio></div></fieldset></div><div class="mt-4 flex flex-wrap items-center justify-between gap-2"><p data-testid="product-count" class="rounded-full px-3 py-1.5 text-sm font-semibold" :class="productCountUnavailable?'bg-error-50 text-error-500':loading?'bg-gray-100 text-gray-500':'bg-primary-50 text-primary-600'">{{productCountLabel}}</p><button type="button" class="rounded-lg px-4 py-2 text-sm font-semibold text-gray-600 transition hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-40" :disabled="!hasActiveFilters" @click="resetFilters">Сбросить</button></div></form><p class="sr-only" role="status" aria-live="polite">{{filterResultStatus}}</p>
<p class="sr-only" role="status" aria-live="polite">{{sortStatus}}</p>
<div class="mt-6 overflow-hidden rounded-xl border border-gray-200 bg-white shadow-card">
  <UiLoadingState v-if="loading" label="Загрузка товаров…" />
  <template v-else>
  <div class="max-w-full overflow-x-auto [contain:paint]" role="region" aria-label="Таблица товаров" tabindex="0">
    <table class="w-full min-w-[1180px] text-left text-sm">
      <caption class="sr-only">Товары каталога. Заголовки SKU, Наименование, Создан и Изменён управляют сортировкой.</caption>
      <thead class="border-b border-gray-200 bg-gray-50 text-xs font-semibold tracking-wide text-gray-500">
        <tr>
          <th scope="col" :aria-sort="ariaSort('name')" class="px-4 py-3"><button type="button" class="inline-flex items-center gap-1.5 rounded-lg px-2 py-1 text-left transition hover:text-primary-600 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:ring-offset-2 disabled:cursor-wait disabled:opacity-60" :disabled="loading" @click="changeSort('name')">Наименование<ArrowUp v-if="sort==='name'&&direction==='asc'" :size="15"/><ArrowDown v-else-if="sort==='name'" :size="15"/><ArrowUpDown v-else :size="15" class="text-gray-400"/></button></th>
          <th scope="col" :aria-sort="ariaSort('sku')" class="px-4 py-3"><button type="button" class="inline-flex items-center gap-1.5 rounded-lg px-2 py-1 transition hover:text-primary-600 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:ring-offset-2 disabled:cursor-wait disabled:opacity-60" :disabled="loading" @click="changeSort('sku')">SKU<ArrowUp v-if="sort==='sku'&&direction==='asc'" :size="15"/><ArrowDown v-else-if="sort==='sku'" :size="15"/><ArrowUpDown v-else :size="15" class="text-gray-400"/></button></th>
          <th scope="col" class="px-4 py-3">Артикул</th><th scope="col" class="px-4 py-3">Категория</th><th scope="col" class="px-4 py-3 text-right">Цена</th><th scope="col" class="px-4 py-3 text-right">Остаток</th><th scope="col" class="px-4 py-3">Статус</th>
          <th scope="col" :aria-sort="ariaSort('created_at')" class="px-4 py-3"><button type="button" class="inline-flex items-center gap-1.5 rounded-lg px-2 py-1 transition hover:text-primary-600 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:ring-offset-2 disabled:cursor-wait disabled:opacity-60" :disabled="loading" @click="changeSort('created_at')">Создан<ArrowUp v-if="sort==='created_at'&&direction==='asc'" :size="15"/><ArrowDown v-else-if="sort==='created_at'" :size="15"/><ArrowUpDown v-else :size="15" class="text-gray-400"/></button></th>
          <th scope="col" :aria-sort="ariaSort('updated_at')" class="px-4 py-3"><button type="button" class="inline-flex items-center gap-1.5 rounded-lg px-2 py-1 transition hover:text-primary-600 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:ring-offset-2 disabled:cursor-wait disabled:opacity-60" :disabled="loading" @click="changeSort('updated_at')">Изменён<ArrowUp v-if="sort==='updated_at'&&direction==='asc'" :size="15"/><ArrowDown v-else-if="sort==='updated_at'" :size="15"/><ArrowUpDown v-else :size="15" class="text-gray-400"/></button></th>
          <th scope="col" class="px-4 py-3 text-right"><span class="sr-only">Действия</span></th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-100">
        <tr v-for="product in products" :key="product.id" class="group transition hover:bg-gray-50">
          <td class="px-4 py-3"><div class="flex min-w-[240px] items-center gap-3"><img v-if="product.primary_image" :src="product.primary_image.url" :alt="product.primary_image.alt||product.name" class="h-11 w-11 shrink-0 rounded-lg object-cover"><span v-else class="grid h-11 w-11 shrink-0 place-items-center rounded-lg bg-primary-50 text-primary-600"><Package :size="19"/></span><div class="min-w-0"><p class="font-semibold text-gray-800" :title="isProductNameTruncated(product.name)?product.name:undefined"><span data-testid="product-name-preview" :aria-hidden="isProductNameTruncated(product.name)?'true':undefined">{{productNamePreview(product.name)}}</span><span v-if="isProductNameTruncated(product.name)" class="sr-only">{{product.name}}</span></p><p class="mt-0.5 text-xs text-gray-500">{{product.brand?.name||'Без бренда'}}</p></div></div></td>
          <td class="whitespace-nowrap px-4 py-3 font-mono text-gray-700">{{product.sku}}</td><td class="whitespace-nowrap px-4 py-3 text-gray-600">{{product.article_number||'—'}}</td><td class="max-w-48 px-4 py-3 text-gray-600"><span class="rounded-full px-2 py-0.5 text-xs font-semibold bg-blue-light-50 text-blue-light-500">{{product.category.name}}</span></td><td class="whitespace-nowrap px-4 py-3 text-right font-medium text-gray-800">{{product.price}} ₽</td><td class="whitespace-nowrap px-4 py-3 text-right text-gray-700">{{product.stock_quantity}}</td>
          <td class="px-4 py-3"><div class="flex min-w-24 flex-col items-start gap-1"><span class="rounded-full px-2 py-0.5 text-xs font-semibold" :class="product.is_active?'bg-success-50 text-success-500':'bg-gray-100 text-gray-700'">{{product.is_active?'Активен':'Скрыт'}}</span><span v-if="product.is_on_sale" class="rounded-full bg-warning-50 px-2 py-0.5 text-xs font-semibold text-warning-500">Распродажа</span></div></td>
          <td class="whitespace-nowrap px-4 py-3 text-gray-600"><time :datetime="product.created_at">{{formatDate(product.created_at)}}</time></td><td class="whitespace-nowrap px-4 py-3 text-gray-600"><time :datetime="product.updated_at">{{formatDate(product.updated_at)}}</time></td>
          <td class="px-4 py-3"><div class="flex justify-end gap-1"><button type="button" :aria-label="`Создать похожий товар ${product.name}`" class="rounded-lg p-2 text-gray-500 transition hover:bg-primary-50 hover:text-primary-600 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:ring-offset-2" @click="cloneProduct(product)"><Copy :size="17"/></button><button type="button" :aria-label="`Редактировать товар ${product.name}`" class="rounded-lg p-2 text-primary-600 transition hover:bg-primary-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:ring-offset-2" @click="open(product)"><Pencil :size="17"/></button><button type="button" :aria-label="`Удалить товар ${product.name}`" class="rounded-lg p-2 text-error-500 transition hover:bg-error-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-error-500 focus-visible:ring-offset-2" @click="confirmError='';deleting=product"><Trash2 :size="17"/></button></div></td>
        </tr>
        <tr v-if="!products.length"><td colspan="10" class="p-12 text-center text-sm text-gray-500">Товары не найдены.</td></tr>
      </tbody>
    </table>
  </div>
  </template>
</div><UiPagination v-if="pagination" :meta="pagination" :loading="loading" :announce="false" @change="load"/>
<UiDialog :open="opened" labelledby="product-editor-title" :close-disabled="saving" :suspended="Boolean(imageDeleting||groupDeleting)" overlay-class="z-50 p-3 sm:p-6" panel-class="mx-auto flex h-full max-w-6xl flex-col overflow-hidden rounded-xl bg-white shadow-xl" @close="close"><header class="flex shrink-0 justify-between border-b border-gray-200 px-5 py-4"><div><h2 id="product-editor-title" class="text-lg font-bold text-gray-900">{{editing?editing.name:'Новый товар'}}</h2></div><button type="button" class="rounded-lg p-1 text-gray-500 transition hover:bg-gray-100 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-primary-50 disabled:cursor-not-allowed disabled:opacity-40" :disabled="saving" aria-label="Закрыть карточку товара" @click="close"><X :size="20"/></button></header><EditorSteps :steps="steps" :active="activeStep" :enabled="enabled" @select="activeStep=$event as Step"/><div data-testid="product-editor-body" class="min-h-0 flex-1 overflow-y-auto p-5 sm:p-6"><p v-if="error" role="alert" class="mb-4 rounded-lg bg-error-50 px-4 py-3 text-sm text-error-500">{{error}}</p><p v-if="success" role="status" class="mb-4 rounded-lg bg-success-50 px-4 py-3 text-sm text-success-500">{{success}}</p>
<ProductMainSection v-if="activeStep==='main'" />
<ProductAttributesSection v-else-if="activeStep==='attributes'" />
<ProductImagesSection v-else-if="activeStep==='images'" />
<ProductVariantsSection v-else-if="activeStep==='group'" />
<div v-else id="product-review" class="space-y-5">
  <ProductReviewSection />
  <ProductRelationsSection />
</div></div><footer data-testid="product-editor-footer" class="shrink-0 border-t border-gray-200 bg-white px-5 py-4 sm:px-6"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-end">
  <button v-if="activeStep==='main'" type="submit" form="product-main-form" class="inline-flex items-center justify-center gap-2 rounded-lg bg-primary-500 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60" :disabled="saving"><Save :size="17"/>{{saving?'Сохранение…':'Сохранить и продолжить'}}</button>
  <button v-else-if="activeStep==='attributes'" type="submit" form="product-attributes-form" class="rounded-lg bg-primary-500 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60" :disabled="saving">{{saving?'Сохранение…':'Сохранить и продолжить'}}</button>
  <button v-else-if="activeStep==='images'" type="button" class="rounded-lg bg-primary-500 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60" :disabled="saving" @click="activeStep='group'">Продолжить</button>
  <template v-else-if="activeStep==='group'">
    <button v-if="selectedGroupId" type="button" class="rounded-lg px-4 py-2.5 text-sm font-semibold text-error-500 disabled:opacity-60 sm:mr-auto" :disabled="saving" @click="confirmError='';groupDeleting=true">Удалить группу</button>
    <button type="button" class="rounded-lg px-4 py-2.5 text-sm font-semibold text-gray-600 disabled:opacity-60" :disabled="saving" @click="activeStep='review'">Не объединять</button>
    <button type="submit" form="product-group-form" class="rounded-lg bg-primary-500 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60" :disabled="saving">{{saving?'Сохранение…':'Сохранить группу'}}</button>
  </template>
  <template v-else>
    <button type="button" class="rounded-lg px-5 py-2.5 text-sm font-semibold text-gray-600 transition hover:bg-gray-50 disabled:opacity-60" :disabled="saving" @click="close">Закрыть</button>
    <button v-if="!form.is_active" type="button" class="rounded-lg bg-success-500 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-success-600 disabled:opacity-60" :disabled="saving" @click="publish">{{saving?'Публикация…':'Опубликовать товар'}}</button>
    <button v-else type="button" class="inline-flex items-center justify-center gap-2 rounded-lg bg-gray-100 px-4 py-2.5 text-sm font-semibold text-gray-700 transition hover:bg-gray-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:ring-offset-2 disabled:opacity-60" :disabled="saving" @click="hideProduct"><EyeOff :size="17"/>{{saving?'Скрытие…':'Скрыть товар'}}</button>
  </template>
</div></footer></UiDialog>
<UiDialog :open="Boolean(deleting)" labelledby="delete-title" :close-disabled="saving" overlay-class="z-[60] grid place-items-center p-4" panel-class="w-full max-w-md rounded-xl bg-white p-6 shadow-xl" @close="confirmError='';deleting=null"><h2 id="delete-title" class="text-lg font-bold">Удалить товар?</h2><p v-if="confirmError" class="mt-3 text-sm text-error-500" role="alert">{{confirmError}}</p><p class="mt-2 text-sm text-gray-500">Будет удалена только эта продаваемая позиция.</p><div class="mt-6 flex justify-end gap-3"><button type="button" :disabled="saving" @click="confirmError='';deleting=null">Отмена</button><button type="button" :disabled="saving" class="rounded-lg bg-error-500 px-4 py-2 text-white disabled:opacity-60" @click="removeProduct">{{saving?'Удаление…':'Удалить'}}</button></div></UiDialog></section>
<UiDialog :open="Boolean(imageDeleting)" labelledby="delete-image-title" :close-disabled="saving" overlay-class="z-[70] grid place-items-center p-4" panel-class="w-full max-w-md rounded-xl bg-white p-6 shadow-xl" @close="confirmError='';imageDeleting=null"><h2 id="delete-image-title" class="text-lg font-bold">Удалить фотографию?</h2><p v-if="confirmError" class="mt-3 text-sm text-error-500" role="alert">{{confirmError}}</p><p class="mt-2 text-sm text-gray-500">Файл будет удалён без возможности восстановления.</p><div class="mt-6 flex justify-end gap-3"><button type="button" :disabled="saving" @click="confirmError='';imageDeleting=null">Отмена</button><button type="button" :disabled="saving" class="rounded-lg bg-error-500 px-4 py-2 text-white disabled:opacity-60" @click="removeImage">{{saving?'Удаление…':'Удалить'}}</button></div></UiDialog>
<UiDialog :open="groupDeleting" labelledby="delete-group-title" :close-disabled="saving" overlay-class="z-[70] grid place-items-center p-4" panel-class="w-full max-w-md rounded-xl bg-white p-6 shadow-xl" @close="confirmError='';groupDeleting=false"><h2 id="delete-group-title" class="text-lg font-bold">Удалить группу вариантов?</h2><p v-if="confirmError" class="mt-3 text-sm text-error-500" role="alert">{{confirmError}}</p><p class="mt-2 text-sm text-gray-500">Товары останутся самостоятельными позициями.</p><div class="mt-6 flex justify-end gap-3"><button type="button" :disabled="saving" @click="confirmError='';groupDeleting=false">Отмена</button><button type="button" :disabled="saving" class="rounded-lg bg-error-500 px-4 py-2 text-white disabled:opacity-60" @click="ungroup">{{saving?'Удаление…':'Удалить группу'}}</button></div></UiDialog>
</template>

<style scoped>
#product-editor-title {
  min-width: 0;
  overflow-wrap: anywhere;
}

header:has(#product-editor-title) > div {
  min-width: 0;
}
</style>
