<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { MessageSquare, RefreshCw } from '@lucide/vue'
import BaseAlert from '../components/BaseAlert.vue'
import BaseInput from '../components/BaseInput.vue'
import BaseSelect from '../components/BaseSelect.vue'
import PaginationControls from '../components/PaginationControls.vue'
import { addOrderComment, getOrder, getOrderComments, getOrderHistory, getOrders, getOrderStatuses, updateOrderPayment, updateOrderStatus, type Order, type OrderComment, type OrderHistory, type OrderStatus } from '../services/orders'
import { useAuthStore } from '../stores/auth'

const auth = useAuthStore()
const orders = ref<Order[]>([]); const selected = ref<Order | null>(null); const statuses = ref<OrderStatus[]>([])
const histories = ref<OrderHistory[]>([]); const comments = ref<OrderComment[]>([])
const search = ref(''); const status = ref(''); const paymentStatus = ref(''); const page = ref(1)
const meta = ref({ current_page: 1, last_page: 1, per_page: 25, total: 0 })
const loading = ref(false); const detailLoading = ref(false); const error = ref(''); const actionError = ref(''); const saving = ref(false); const commentBody = ref('')
const canManage = computed(() => auth.hasPermission('orders.manage')); const canManagePayment = computed(() => auth.hasPermission('payments.manage'))
const statusOptions = computed(() => [{ label: 'Все статусы', value: '' }, ...statuses.value.map((item) => ({ label: item.name, value: item.code }))])
const paymentOptions = [{ label: 'Все оплаты', value: '' }, { label: 'Не оплачено', value: 'not_paid' }, { label: 'Ожидает оплаты', value: 'pending' }, { label: 'Оплачено', value: 'paid' }, { label: 'Частично оплачено', value: 'partially_paid' }, { label: 'Возврат', value: 'refunded' }]
const paymentEditOptions = paymentOptions.slice(1)
const paymentForm = ref({ payment_status: 'not_paid', payment_amount: '', payment_method: '', payment_reference: '' })

function date(value: string | null): string { return value ? new Date(value).toLocaleString('ru-RU') : '—' }
function amount(value: string | null): string { return value === null ? '—' : new Intl.NumberFormat('ru-RU', { style: 'currency', currency: 'RUB' }).format(Number(value)) }
function statusName(code: string): string { return statuses.value.find((item) => item.code === code)?.name ?? code }
async function load(nextPage = 1): Promise<void> { loading.value = true; error.value = ''; try { const response = await getOrders({ search: search.value, status: status.value, payment_status: paymentStatus.value }, { page: nextPage }); orders.value = response.data; meta.value = response.meta; page.value = response.meta.current_page } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Не удалось загрузить заказы.' } finally { loading.value = false } }
async function selectOrder(order: Order): Promise<void> { detailLoading.value = true; actionError.value = ''; try { selected.value = await getOrder(order.id); const [nextHistory, nextComments] = await Promise.all([getOrderHistory(order.id), getOrderComments(order.id)]); histories.value = nextHistory; comments.value = nextComments; syncPaymentForm() } catch (reason) { actionError.value = reason instanceof Error ? reason.message : 'Не удалось загрузить детали заказа.' } finally { detailLoading.value = false } }
function syncPaymentForm(): void { if (!selected.value) return; paymentForm.value = { payment_status: selected.value.payment_status, payment_amount: selected.value.payment_amount ?? '', payment_method: selected.value.payment_method ?? '', payment_reference: selected.value.payment_reference ?? '' } }
async function changeStatus(): Promise<void> { if (!selected.value) return; saving.value = true; actionError.value = ''; try { await updateOrderStatus(selected.value.id, selected.value.status); await selectOrder(selected.value); await load(page.value) } catch (reason) { actionError.value = reason instanceof Error ? reason.message : 'Не удалось изменить статус.' } finally { saving.value = false } }
async function savePayment(): Promise<void> { if (!selected.value) return; saving.value = true; actionError.value = ''; try { const payload = paymentForm.value.payment_status === 'not_paid' || paymentForm.value.payment_status === 'pending' ? { payment_status: paymentForm.value.payment_status } : { ...paymentForm.value, paid_at: new Date().toISOString() }; await updateOrderPayment(selected.value.id, payload); await selectOrder(selected.value); await load(page.value) } catch (reason) { actionError.value = reason instanceof Error ? reason.message : 'Не удалось сохранить оплату.' } finally { saving.value = false } }
async function submitComment(): Promise<void> { if (!selected.value || !commentBody.value.trim()) return; saving.value = true; actionError.value = ''; try { await addOrderComment(selected.value.id, commentBody.value); commentBody.value = ''; comments.value = await getOrderComments(selected.value.id) } catch (reason) { actionError.value = reason instanceof Error ? reason.message : 'Не удалось добавить комментарий.' } finally { saving.value = false } }
watch([status, paymentStatus], () => void load())
onMounted(async () => { try { statuses.value = await getOrderStatuses() } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Не удалось загрузить статусы.' }; await load() })
</script>

<template>
  <section class="mx-auto admin-page"><div class="mb-7"><p class="text-sm font-medium text-gray-500">Продажи</p><h1 class="mt-1 text-2xl font-bold tracking-tight text-gray-900 sm:text-3xl">Заказы</h1><p class="mt-2 text-sm text-gray-500">Просматривайте состав и данные заказа, статусы, оплату и внутренние комментарии.</p></div>
    <BaseAlert v-if="error" class="mb-4">{{ error }}</BaseAlert>
    <div class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_minmax(380px,0.9fr)]"><div class="rounded-xl border border-gray-200 bg-white shadow-card"><div class="grid gap-3 border-b border-gray-100 p-4 sm:grid-cols-2"><BaseInput v-model="search" searchable placeholder="Номер, клиент, телефон или email" aria-label="Поиск заказов" @keyup.enter="() => load()"/><BaseSelect v-model="status" :options="statusOptions" accessible-name="Статус заказа"/><BaseSelect v-model="paymentStatus" :options="paymentOptions" accessible-name="Статус оплаты"/><button class="inline-flex items-center justify-center gap-2 rounded-lg border border-gray-300 px-4 py-2.5 text-sm font-semibold text-gray-600 hover:bg-gray-25" @click="() => load()"><RefreshCw :size="17" aria-hidden="true"/>Найти</button></div><div class="overflow-x-auto"><table class="w-full min-w-[680px] text-left text-sm"><thead class="bg-gray-25 text-xs font-medium text-gray-500"><tr><th class="px-5 py-3">Заказ</th><th class="px-5 py-3">Клиент</th><th class="px-5 py-3">Статус</th><th class="px-5 py-3">Сумма</th></tr></thead><tbody><tr v-if="loading"><td colspan="4" class="px-5 py-8 text-gray-500" role="status">Загрузка…</td></tr><tr v-else-if="!orders.length"><td colspan="4" class="px-5 py-8 text-gray-500" role="status">Заказы не найдены.</td></tr><tr v-for="order in orders" :key="order.id" class="border-t border-gray-100 text-gray-600" :class="selected?.id === order.id ? 'bg-primary-50' : ''"><td class="px-5 py-4"><button type="button" class="-m-2 rounded-lg p-2 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500" :aria-label="`Открыть заказ ${order.order_number}`" :aria-current="selected?.id === order.id ? 'true' : undefined" @click="selectOrder(order)"><span class="block font-semibold text-gray-800">{{ order.order_number }}</span><span class="mt-1 block text-xs text-gray-500">{{ date(order.created_at) }}</span></button></td><td class="px-5 py-4"><p class="font-medium text-gray-700">{{ order.customer.name }}</p><p class="mt-1 text-xs text-gray-500">{{ order.customer.phone }}</p></td><td class="px-5 py-4"><span class="rounded-full bg-primary-50 px-2.5 py-1 text-xs font-medium text-primary-700">{{ statusName(order.status) }}</span><p class="mt-2 text-xs text-gray-500">{{ paymentOptions.find((item) => item.value === order.payment_status)?.label }}</p></td><td class="px-5 py-4 font-semibold text-gray-700">{{ amount(order.total_amount) }}</td></tr></tbody></table></div><PaginationControls :meta="meta" :loading="loading" class="border-t border-gray-100 px-5 py-4" @change="load"/></div>
      <aside class="min-w-0 rounded-xl border border-gray-200 bg-white shadow-card"><div v-if="detailLoading" class="p-8 text-sm text-gray-500" role="status">Загрузка деталей…</div><div v-else-if="!selected" class="p-8 text-sm text-gray-500" role="status">Выберите заказ в списке, чтобы открыть рабочее место менеджера.</div><div v-else class="space-y-6 p-5"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-medium text-gray-500">Заказ</p><h2 class="mt-1 text-xl font-bold text-gray-900">{{ selected.order_number }}</h2></div><strong class="text-lg text-gray-800">{{ amount(selected.total_amount) }}</strong></div><BaseAlert v-if="actionError">{{ actionError }}</BaseAlert>
        <section><h3 class="text-sm font-semibold text-gray-900">Клиент и доставка</h3><dl class="mt-3 space-y-2 text-sm text-gray-600"><div><dt class="text-xs text-gray-500">Клиент</dt><dd>{{ selected.customer.name }} · {{ selected.customer.phone }}</dd><dd v-if="selected.customer.email">{{ selected.customer.email }}</dd></div><div><dt class="text-xs text-gray-500">Адрес</dt><dd class="whitespace-pre-line">{{ selected.delivery_address }}</dd></div><div v-if="selected.customer_comment"><dt class="text-xs text-gray-500">Комментарий клиента</dt><dd class="whitespace-pre-line">{{ selected.customer_comment }}</dd></div></dl></section>
        <section><h3 class="text-sm font-semibold text-gray-900">Состав заказа</h3><ul class="mt-3 divide-y divide-gray-100 rounded-lg border border-gray-200"><li v-for="item in selected.items" :key="`${item.product_id}-${item.product_name}`" class="flex justify-between gap-3 p-3 text-sm"><span><b class="text-gray-800">{{ item.product_name }}</b><small class="mt-1 block text-gray-500">{{ item.product_sku ?? 'Без SKU' }} · {{ item.quantity }} шт.</small></span><strong class="whitespace-nowrap text-gray-700">{{ amount(item.line_total) }}</strong></li></ul></section>
        <section v-if="canManage" class="rounded-lg border border-gray-200 p-4"><h3 class="text-sm font-semibold text-gray-900">Статус заказа</h3><div class="mt-3 flex gap-2"><BaseSelect v-model="selected.status" class="min-w-0 flex-1" :options="statuses.map((item) => ({ label: item.name, value: item.code }))" accessible-name="Новый статус заказа"/><button :disabled="saving" class="rounded-lg bg-primary-500 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50" @click="changeStatus">Сохранить</button></div></section>
        <section v-if="canManagePayment" class="rounded-lg border border-gray-200 p-4"><h3 class="text-sm font-semibold text-gray-900">Оплата</h3><div class="mt-3 grid gap-3"><BaseSelect v-model="paymentForm.payment_status" :options="paymentEditOptions" accessible-name="Статус оплаты"/><template v-if="!['not_paid', 'pending'].includes(paymentForm.payment_status)"><BaseInput v-model="paymentForm.payment_amount" type="number" min="0.01" step="0.01" placeholder="Сумма" aria-label="Сумма оплаты"/><BaseInput v-model="paymentForm.payment_method" placeholder="Способ оплаты" aria-label="Способ оплаты"/><BaseInput v-model="paymentForm.payment_reference" placeholder="Номер документа (необязательно)" aria-label="Номер документа"/></template><button :disabled="saving" class="rounded-lg bg-primary-500 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50" @click="savePayment">Сохранить оплату</button></div></section>
        <section><h3 class="text-sm font-semibold text-gray-900">История статусов</h3><ol class="mt-3 space-y-2 border-l border-gray-200 pl-4 text-sm"><li v-for="entry in histories" :key="entry.id"><p class="text-gray-700">{{ statusName(entry.from_status) }} → <b>{{ statusName(entry.to_status) }}</b></p><p class="text-xs text-gray-500">{{ entry.actor?.name ?? 'Система' }} · {{ date(entry.occurred_at) }}</p></li><li v-if="!histories.length" class="text-gray-500">Изменений статуса пока нет.</li></ol></section>
        <section><h3 class="text-sm font-semibold text-gray-900">Внутренние комментарии</h3><div class="mt-3 space-y-3"><article v-for="comment in comments" :key="comment.id" class="rounded-lg bg-gray-25 p-3 text-sm"><p class="whitespace-pre-line text-gray-700">{{ comment.body }}</p><p class="mt-2 text-xs text-gray-500">{{ comment.author?.name ?? 'Система' }} · {{ date(comment.created_at) }}</p></article><p v-if="!comments.length" class="text-sm text-gray-500">Комментариев пока нет.</p></div><form v-if="canManage" class="mt-3" @submit.prevent="submitComment"><label class="sr-only" for="order-comment">Новый внутренний комментарий</label><textarea id="order-comment" v-model="commentBody" class="w-full rounded-lg border border-gray-300 p-3 text-sm outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-100" rows="3" placeholder="Добавить внутренний комментарий"/><button :disabled="saving || !commentBody.trim()" class="mt-2 inline-flex items-center gap-2 rounded-lg border border-gray-300 px-3 py-2 text-sm font-semibold text-gray-700 disabled:opacity-50"><MessageSquare :size="16"/>Добавить</button></form></section>
      </div></aside></div></section>
</template>
