<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { Plus, Save, Trash2 } from '@lucide/vue'
import BaseInput from '../components/BaseInput.vue'
import BaseSelect from '../components/BaseSelect.vue'
import { getAllProducts, type Product } from '../services/products'
import { getProductRelations, saveProductRelations, type ProductRelationType } from '../services/productRelations'
import { useAuthStore } from '../stores/auth'

type RelationForm = { related_product_id: string; type: ProductRelationType; sort_order: string }
const auth = useAuthStore(); const products = ref<Product[]>([]); const selectedProductId = ref(''); const relations = ref<RelationForm[]>([]); const error = ref(''); const saving = ref(false)
const canManage = computed(() => auth.hasPermission('catalog.manage')); const productOptions = computed(() => products.value.map((product) => ({ value: String(product.id), label: product.name }))); const relatedProductOptions = computed(() => productOptions.value.filter((product) => product.value !== selectedProductId.value)); const typeOptions = [{ value: 'related', label: 'Связанный товар' }, { value: 'recommended', label: 'Рекомендуемый товар' }]
function add(): void { const first = relatedProductOptions.value[0]?.value ?? ''; relations.value.push({ related_product_id: first, type: 'related', sort_order: String(relations.value.length) }) }
async function loadProducts(): Promise<void> { try { products.value = await getAllProducts() } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Не удалось загрузить товары.' } }
async function loadRelations(): Promise<void> { if (!selectedProductId.value) { relations.value = []; return }; try { relations.value = (await getProductRelations(Number(selectedProductId.value))).map((relation) => ({ related_product_id: String(relation.related_product_id), type: relation.type, sort_order: String(relation.sort_order) })) } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Не удалось загрузить связи.' } }
async function save(): Promise<void> { if (!selectedProductId.value) return; saving.value = true; try { await saveProductRelations(Number(selectedProductId.value), { relations: relations.value.map((relation) => ({ related_product_id: Number(relation.related_product_id), type: relation.type, sort_order: Number(relation.sort_order) })) }); await loadRelations() } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Не удалось сохранить связи.' } finally { saving.value = false } }
watch(selectedProductId, () => void loadRelations()); onMounted(loadProducts)
</script>
<template>
  <section class="mx-auto admin-page"><div class="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-medium text-gray-500">Каталог</p><h1 class="mt-1 text-2xl font-bold tracking-tight text-gray-900 sm:text-3xl">Связанные товары</h1><p class="mt-2 text-sm text-gray-500">Добавьте связанные или рекомендуемые товары для карточки товара.</p></div><button v-if="canManage && selectedProductId" class="inline-flex items-center gap-2 rounded-lg bg-primary-500 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-primary-600 disabled:opacity-60" :disabled="saving" @click="save"><Save :size="18" />{{ saving ? 'Сохранение…' : 'Сохранить' }}</button></div><p v-if="error" class="mb-4 rounded-lg border border-error-200 bg-error-50 px-4 py-3 text-sm text-error-500">{{ error }}</p><label class="mb-5 block max-w-xl text-sm font-medium text-gray-700">Товар<BaseSelect v-model="selectedProductId" class="mt-1.5" :options="productOptions" placeholder="Выберите товар" accessible-name="Товар" searchable /></label><div v-if="selectedProductId" class="rounded-xl border border-gray-200 bg-white p-5 shadow-card"><div v-if="relations.length" class="space-y-3"><div v-for="(relation, index) in relations" :key="index" class="grid gap-3 rounded-xl border border-gray-100 bg-gray-25 p-4 sm:grid-cols-[minmax(0,1fr)_180px_110px_auto]"><BaseSelect v-model="relation.related_product_id" :options="relatedProductOptions" placeholder="Выберите товар" :accessible-name="`Связанный товар ${index + 1}`" searchable /><BaseSelect v-model="relation.type" :options="typeOptions" accessible-name="Тип связи" /><BaseInput v-model="relation.sort_order" type="number" min="0" aria-label="Порядок" /><button v-if="canManage" class="rounded-lg p-2 text-error-500 hover:bg-error-50" type="button" aria-label="Удалить связь" @click="relations.splice(index, 1)"><Trash2 :size="18" /></button></div></div><p v-else class="py-7 text-center text-sm text-gray-500">Связанных товаров пока нет.</p><button v-if="canManage" class="mt-4 inline-flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-semibold text-primary-600 hover:bg-primary-50" type="button" :disabled="!relatedProductOptions.length" @click="add"><Plus :size="17" />Добавить связь</button></div><div v-else class="rounded-xl border border-dashed border-gray-300 px-5 py-14 text-center text-sm text-gray-500">Выберите товар, чтобы настроить связанные товары.</div></section>
</template>
