<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { Save } from '@lucide/vue'
import BaseCheckbox from '../components/BaseCheckbox.vue'
import BaseInput from '../components/BaseInput.vue'
import BaseSelect from '../components/BaseSelect.vue'
import type { Attribute } from '../services/attributes'
import { getAllProducts, type Product } from '../services/products'
import { getCategoryAttributes, getProductAttributeValues, saveProductAttributeValues } from '../services/productAttributes'
import { useAuthStore } from '../stores/auth'

const auth = useAuthStore(); const products = ref<Product[]>([]); const attributes = ref<Attribute[]>([]); const selectedProductId = ref(''); const values = ref<Record<number, string>>({}); const error = ref(''); const saving = ref(false)
const canManage = computed(() => auth.hasPermission('catalog.manage'))
const productOptions = computed(() => products.value.map((product) => ({ value: String(product.id), label: product.name })))
function valueToInput(value: unknown): string { if (Array.isArray(value)) return value.join(', '); if (typeof value === 'boolean') return value ? 'true' : 'false'; return String(value ?? '') }
function options(attribute: Attribute): Array<{ value: string; label: string }> { return attribute.options.map((option) => ({ value: option.value, label: option.label })) }
async function loadProducts(): Promise<void> { try { products.value = await getAllProducts() } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Не удалось загрузить товары.' } }
async function loadAttributes(): Promise<void> { if (!selectedProductId.value) { attributes.value = []; return }; try { const product = products.value.find((item) => item.id === Number(selectedProductId.value)); if (!product) return; const [assigned, current] = await Promise.all([getCategoryAttributes(product.category_id), getProductAttributeValues(product.id)]); attributes.value = assigned; const saved = new Map(current.map((item) => [item.attribute_id, item.value])); values.value = Object.fromEntries(assigned.map((attribute) => [attribute.id, valueToInput(saved.get(attribute.id))])) } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Не удалось загрузить характеристики.' } }
function valueFor(attribute: Attribute): string | number | boolean | string[] { const value = values.value[attribute.id] ?? ''; if (attribute.type === 'number') return Number(value); if (attribute.type === 'boolean') return value === 'true'; if (attribute.type === 'multiselect') return value.split(',').map((item) => item.trim()).filter(Boolean); return value }
async function save(): Promise<void> { if (!selectedProductId.value) return; saving.value = true; try { const payload = { attributes: attributes.value.filter((attribute) => attribute.is_required || (values.value[attribute.id] ?? '') !== '').map((attribute) => ({ attribute_id: attribute.id, value: valueFor(attribute) })) }; await saveProductAttributeValues(Number(selectedProductId.value), payload); await loadAttributes() } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Не удалось сохранить характеристики.' } finally { saving.value = false } }
watch(selectedProductId, () => void loadAttributes()); onMounted(loadProducts)
</script>
<template>
  <section class="mx-auto admin-page"><div class="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-medium text-gray-500">Каталог</p><h1 class="mt-1 text-2xl font-bold tracking-tight text-gray-900 sm:text-3xl">Характеристики товаров</h1><p class="mt-2 text-sm text-gray-500">Значения ограничены характеристиками, назначенными категории товара.</p></div><button v-if="canManage && selectedProductId" class="inline-flex items-center gap-2 rounded-lg bg-primary-500 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-primary-600 disabled:opacity-60" :disabled="saving" @click="save"><Save :size="18" />{{ saving ? 'Сохранение…' : 'Сохранить' }}</button></div><p v-if="error" class="mb-4 rounded-lg border border-error-200 bg-error-50 px-4 py-3 text-sm text-error-500">{{ error }}</p><label class="mb-5 block max-w-xl text-sm font-medium text-gray-700">Товар<BaseSelect v-model="selectedProductId" class="mt-1.5" :options="productOptions" placeholder="Выберите товар" accessible-name="Товар" searchable /></label><div v-if="selectedProductId" class="rounded-xl border border-gray-200 bg-white p-5 shadow-card"><div v-if="attributes.length" class="grid gap-5 sm:grid-cols-2"><label v-for="attribute in attributes" :key="attribute.id" class="text-sm font-medium text-gray-700">{{ attribute.name }}<span v-if="attribute.is_required" class="ml-1 text-error-500">*</span><span v-if="attribute.unit" class="ml-1 text-gray-400">({{ attribute.unit }})</span><BaseInput v-if="attribute.type === 'text' || attribute.type === 'number'" :model-value="values[attribute.id] ?? ''" class="mt-1.5" :type="attribute.type === 'number' ? 'number' : 'text'" :required="attribute.is_required" @update:model-value="values[attribute.id] = $event" /><BaseSelect v-else-if="attribute.type === 'select'" v-model="values[attribute.id]" class="mt-1.5" :options="options(attribute)" placeholder="Выберите значение" :accessible-name="attribute.name" /><BaseInput v-else-if="attribute.type === 'multiselect'" :model-value="values[attribute.id] ?? ''" class="mt-1.5" :required="attribute.is_required" placeholder="Через запятую" @update:model-value="values[attribute.id] = $event" /><BaseCheckbox v-else :checked="values[attribute.id] === 'true'" class="mt-2" mode="boolean" @update:checked="values[attribute.id] = $event ? 'true' : 'false'">Да</BaseCheckbox><p v-if="attribute.type === 'multiselect'" class="mt-1 text-xs font-normal text-gray-400">Допустимые значения: {{ attribute.options.map((option) => option.label).join(', ') }}</p></label></div><p v-else class="py-10 text-center text-sm text-gray-500">Для категории этого товара характеристики пока не назначены.</p></div><div v-else class="rounded-xl border border-dashed border-gray-300 px-5 py-14 text-center text-sm text-gray-500">Выберите товар, чтобы заполнить его характеристики.</div></section>
</template>
