<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { GripVertical, ImagePlus, Package, Pencil, Plus, Save, Search, Star, Trash2, X } from '@lucide/vue'
import BaseCheckbox from '../components/BaseCheckbox.vue'
import BaseInput from '../components/BaseInput.vue'
import BaseSelect from '../components/BaseSelect.vue'
import BaseTextarea from '../components/BaseTextarea.vue'
import AttributeValueField, { type AttributeDraftValue } from '../components/AttributeValueField.vue'
import PaginationControls from '../components/PaginationControls.vue'
import type { Attribute } from '../services/attributes'
import { getAllBrands, type Brand } from '../services/brands'
import { getCategories, type Category } from '../services/categories'
import { getCategoryAttributes, getProductAttributeValues, saveProductAttributeValues } from '../services/productAttributes'
import { deleteProductImage, getAllProductImages, getAllProductImages as getProductImages, updateProductImage, uploadProductImage, type ProductImage } from '../services/productImages'
import { getProductRelations, saveProductRelations, type ProductRelationType } from '../services/productRelations'
import { deleteProduct, getAllProducts, getProducts, saveProduct, type Product, type ProductFilters, type ProductPayload } from '../services/products'
import type { PaginationMeta } from '../services/pagination'
import { deleteProductVariant, getAllProductVariants, getAllProductVariants as getProductVariants, saveProductVariant, type ProductVariant, type ProductVariantPayload } from '../services/productVariants'
import { useAuthStore } from '../stores/auth'

type Tab = 'main' | 'variants' | 'attributes' | 'images' | 'relations'
type VariantAttributeForm = { attribute_id: string; value: AttributeDraftValue }
type VariantForm = { name: string; sku: string; price: string; old_price: string; stock_quantity: string; is_active: boolean; sort_order: string; attribute_values: VariantAttributeForm[] }
type ImageForm = { alt: string }
type RelationForm = { related_product_id: string; type: ProductRelationType; sort_order: string }

const auth = useAuthStore()
const products = ref<Product[]>([])
const relationProducts = ref<Product[]>([])
const pagination = ref<PaginationMeta | null>(null)
const categories = ref<Category[]>([])
const brands = ref<Brand[]>([])
const error = ref('')
const loading = ref(false)
const saving = ref(false)
const opened = ref(false)
const activeTab = ref<Tab>('main')
const editing = ref<Product | null>(null)
const deleting = ref<Product | null>(null)
const isDeleting = ref(false)
const manuallyEditedSlug = ref(false)
const filters = ref({ search: '', category_id: '', brand_id: '', is_active: '', has_stock: '', price_from: '', price_to: '' })
const form = ref<ProductPayload>({ category_id: 0, brand_id: null, name: '', slug: '', description: '', is_active: true })
const variants = ref<ProductVariant[]>([])
const variantEditor = ref<ProductVariant | null>(null)
const variantEditorOpen = ref(false)
const variantForm = ref<VariantForm>({ name: '', sku: '', price: '0.00', old_price: '', stock_quantity: '0', is_active: true, sort_order: '0', attribute_values: [] })
const attributes = ref<Attribute[]>([])
const attributeValues = ref<Record<number, AttributeDraftValue>>({})
const images = ref<ProductImage[]>([])
const draggedImageId = ref<number | null>(null)
const selectedFile = ref<File | null>(null)
const imageInput = ref<HTMLInputElement | null>(null)
const imageForm = ref<ImageForm>({ alt: '' })
const imageDrafts = ref<Record<number, ImageForm>>({})
const relations = ref<RelationForm[]>([])

const canManage = computed(() => auth.hasPermission('catalog.manage'))
const tabs = computed(() => [
  { id: 'main' as Tab, label: 'Основное' }, { id: 'variants' as Tab, label: 'Варианты' },
  { id: 'attributes' as Tab, label: 'Характеристики' }, { id: 'images' as Tab, label: 'Фото' }, { id: 'relations' as Tab, label: 'Связи' },
])
function flatten(nodes: Category[], depth = 0): Array<Category & { depth: number }> { return nodes.flatMap((item) => [{ ...item, depth }, ...flatten(item.children ?? [], depth + 1)]) }
const categoryOptions = computed(() => flatten(categories.value).filter((item) => item.is_active).map((item) => ({ value: String(item.id), label: `${'— '.repeat(item.depth)}${item.name}` })))
const filterCategoryOptions = computed(() => [{ value: '', label: 'Все категории' }, ...categoryOptions.value])
const brandOptions = computed(() => [{ value: '', label: 'Без бренда' }, ...brands.value.map((item) => ({ value: String(item.id), label: item.name }))])
const filterBrandOptions = computed(() => [{ value: '', label: 'Все бренды' }, ...brands.value.map((item) => ({ value: String(item.id), label: item.name }))])
const stateOptions = [{ value: '', label: 'Любая активность' }, { value: '1', label: 'Активные' }, { value: '0', label: 'Скрытые' }]
const stockOptions = [{ value: '', label: 'Любой остаток' }, { value: '1', label: 'В наличии' }, { value: '0', label: 'Нет в наличии' }]
const selectedCategory = computed({ get: () => form.value.category_id ? String(form.value.category_id) : '', set: (value: string) => { form.value.category_id = Number(value) } })
const selectedBrand = computed({ get: () => form.value.brand_id === null ? '' : String(form.value.brand_id), set: (value: string) => { form.value.brand_id = value ? Number(value) : null } })
const relatedProductOptions = computed(() => relationProducts.value.filter((product) => product.id !== editing.value?.id).map((product) => ({ value: String(product.id), label: product.name })))
const relationTypeOptions = [{ value: 'related', label: 'Связанный товар' }, { value: 'recommended', label: 'Рекомендуемый товар' }]

const transliteration: Record<string, string> = { а: 'a', б: 'b', в: 'v', г: 'g', д: 'd', е: 'e', ё: 'yo', ж: 'zh', з: 'z', и: 'i', й: 'y', к: 'k', л: 'l', м: 'm', н: 'n', о: 'o', п: 'p', р: 'r', с: 's', т: 't', у: 'u', ф: 'f', х: 'kh', ц: 'ts', ч: 'ch', ш: 'sh', щ: 'shch', ъ: '', ы: 'y', ь: '', э: 'e', ю: 'yu', я: 'ya' }
function slugify(value: string): string { return Array.from(value.toLowerCase(), (character) => transliteration[character] ?? character).join('').normalize('NFKD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') }
function updateName(value: string): void { form.value.name = value; if (!manuallyEditedSlug.value) form.value.slug = slugify(value) }
function productFilters(): ProductFilters { return { search: filters.value.search || undefined, category_id: filters.value.category_id ? Number(filters.value.category_id) : undefined, brand_id: filters.value.brand_id ? Number(filters.value.brand_id) : undefined, is_active: filters.value.is_active === '' ? undefined : filters.value.is_active === '1', has_stock: filters.value.has_stock === '' ? undefined : filters.value.has_stock === '1', price_from: filters.value.price_from || undefined, price_to: filters.value.price_to || undefined } }
async function load(page?: number | SubmitEvent): Promise<void> { const requestedPage = typeof page === 'number' ? page : page instanceof SubmitEvent ? 1 : pagination.value?.current_page ?? 1; loading.value = true; try { const [productPage, categoryList, brandList] = await Promise.all([getProducts({ ...productFilters(), page: requestedPage }), getCategories(), getAllBrands()]); products.value = productPage.data; pagination.value = productPage.meta; categories.value = categoryList; brands.value = brandList } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Не удалось загрузить товары.' } finally { loading.value = false } }
function resetFilters(): void { filters.value = { search: '', category_id: '', brand_id: '', is_active: '', has_stock: '', price_from: '', price_to: '' }; void load() }
function resetDetails(): void { variants.value = []; variantEditor.value = null; variantEditorOpen.value = false; attributes.value = []; attributeValues.value = {}; images.value = []; draggedImageId.value = null; selectedFile.value = null; imageForm.value = { alt: '' }; imageDrafts.value = {}; relations.value = [] }
function setImages(imageList: ProductImage[]): void { images.value = imageList; imageDrafts.value = Object.fromEntries(imageList.map((image) => [image.id, { alt: image.alt ?? '' }])) }
async function loadDetails(product: Product): Promise<void> { try { const [variantList, categoryAttributes, currentAttributes, imageList, relationList, allProducts] = await Promise.all([getAllProductVariants(product.id), getCategoryAttributes(product.category_id), getProductAttributeValues(product.id), getAllProductImages(product.id), getProductRelations(product.id), getAllProducts()]); variants.value = variantList; attributes.value = categoryAttributes; const saved = new Map(currentAttributes.map((item) => [item.attribute_id, item.value])); attributeValues.value = Object.fromEntries(categoryAttributes.map((attribute) => [attribute.id, saved.has(attribute.id) ? valueToInput(saved.get(attribute.id)) : emptyDraftValue(attribute)])); setImages(imageList); relations.value = relationList.map((relation) => ({ related_product_id: String(relation.related_product_id), type: relation.type, sort_order: String(relation.sort_order) })); relationProducts.value = allProducts } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Не удалось загрузить данные товара.' } }
function open(product: Product | null = null): void { error.value = ''; editing.value = product; manuallyEditedSlug.value = product !== null; activeTab.value = 'main'; resetDetails(); form.value = product ? { category_id: product.category_id, brand_id: product.brand_id, name: product.name, slug: product.slug, description: product.description ?? '', is_active: product.is_active } : { category_id: 0, brand_id: null, name: '', slug: '', description: '', is_active: true }; opened.value = true; if (product) void loadDetails(product) }
function close(): void { opened.value = false; editing.value = null }
async function saveMain(): Promise<void> { saving.value = true; try { const saved = await saveProduct(editing.value?.id ?? null, form.value); editing.value = saved; manuallyEditedSlug.value = true; await load(); await loadDetails(saved) } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Не удалось сохранить товар.' } finally { saving.value = false } }
function typedValue(attribute: Attribute, value: AttributeDraftValue): string | number | boolean | string[] { if (attribute.type === 'integer') return Number.parseInt(String(value), 10); if (attribute.type === 'decimal') return Number(value); if (attribute.type === 'boolean') return value === 'true'; if (attribute.type === 'multiselect') return Array.isArray(value) ? value : []; return String(value) }
function emptyDraftValue(attribute: Attribute): AttributeDraftValue { if (attribute.type === 'boolean') return 'false'; if (attribute.type === 'multiselect') return []; return '' }
function variantAttribute(attributeId: string): Attribute | undefined { return attributes.value.find((attribute) => attribute.id === Number(attributeId)) }
function variantAttributeOptions(index: number): Array<{ value: string; label: string }> { const selected = variantForm.value.attribute_values.filter((_, itemIndex) => itemIndex !== index).map((item) => item.attribute_id); return attributes.value.filter((attribute) => !selected.includes(String(attribute.id))).map((attribute) => ({ value: String(attribute.id), label: attribute.name })) }
function addVariantAttribute(): void { const used = variantForm.value.attribute_values.map((item) => item.attribute_id); const attribute = attributes.value.find((item) => !used.includes(String(item.id))); if (attribute) variantForm.value.attribute_values.push({ attribute_id: String(attribute.id), value: emptyDraftValue(attribute) }) }
function changeVariantAttribute(index: number, attributeId: string): void { variantForm.value.attribute_values[index].attribute_id = attributeId; const attribute = variantAttribute(attributeId); variantForm.value.attribute_values[index].value = attribute ? emptyDraftValue(attribute) : '' }
function openVariant(variant: ProductVariant | null = null): void { variantEditor.value = variant; variantEditorOpen.value = true; variantForm.value = variant ? { name: variant.name, sku: variant.sku, price: variant.price, old_price: variant.old_price ?? '', stock_quantity: String(variant.stock_quantity), is_active: variant.is_active, sort_order: String(variant.sort_order), attribute_values: variant.attribute_values.map((item) => ({ attribute_id: String(item.attribute_id), value: valueToInput(item.value) })) } : { name: '', sku: '', price: '0.00', old_price: '', stock_quantity: '0', is_active: true, sort_order: String(variants.value.length), attribute_values: [] } }
async function saveVariant(): Promise<void> { if (!editing.value) return; const invalid = variantForm.value.attribute_values.find((item) => { const attribute = variantAttribute(item.attribute_id); return !attribute || !isValidDraftValue(attribute, item.value) }); if (invalid) { const attribute = variantAttribute(invalid.attribute_id); error.value = `Проверьте значение характеристики «${attribute?.name ?? 'не выбрана'}».`; return } saving.value = true; try { const payload: ProductVariantPayload = { name: variantForm.value.name, sku: variantForm.value.sku, price: variantForm.value.price, old_price: variantForm.value.old_price || null, stock_quantity: Number(variantForm.value.stock_quantity), is_active: variantForm.value.is_active, sort_order: Number(variantForm.value.sort_order), attribute_values: variantForm.value.attribute_values.map((item) => { const attribute = variantAttribute(item.attribute_id); return { attribute_id: Number(item.attribute_id), value: attribute ? typedValue(attribute, item.value) : item.value } }) }; await saveProductVariant(editing.value.id, variantEditor.value?.id ?? null, payload); variantEditor.value = null; variantEditorOpen.value = false; variants.value = await getProductVariants(editing.value.id) } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Не удалось сохранить вариант.' } finally { saving.value = false } }
async function removeVariant(variant: ProductVariant): Promise<void> { if (!editing.value || !confirm(`Удалить вариант «${variant.name}»?`)) return; saving.value = true; try { await deleteProductVariant(editing.value.id, variant.id); variants.value = await getProductVariants(editing.value.id) } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Не удалось удалить вариант.' } finally { saving.value = false } }
function valueToInput(value: unknown): AttributeDraftValue { if (Array.isArray(value)) return value.map(String); if (typeof value === 'boolean') return value ? 'true' : 'false'; return String(value ?? '') }
function valueFor(attribute: Attribute): string | number | boolean | string[] { return typedValue(attribute, attributeValues.value[attribute.id] ?? '') }
function hasDraftValue(value: AttributeDraftValue | undefined): boolean { return Array.isArray(value) ? value.length > 0 : (value ?? '') !== '' }
function isValidDraftValue(attribute: Attribute, value: AttributeDraftValue): boolean { const text = String(value); if (attribute.type === 'string') return typeof value === 'string' && value.length > 0 && value.length <= 255; if (attribute.type === 'text') return typeof value === 'string' && value.length > 0 && value.length <= 10000; if (attribute.type === 'integer') return /^-?\d+$/.test(text); if (attribute.type === 'decimal') return text.trim() !== '' && Number.isFinite(Number(text)); if (attribute.type === 'boolean') return value === 'true' || value === 'false'; if (attribute.type === 'select') return attribute.options.some(option => option.value === value); if (attribute.type === 'multiselect') return Array.isArray(value) && value.length > 0 && new Set(value).size === value.length && value.every(item => attribute.options.some(option => option.value === item)); if (!/^\d{4}-\d{2}-\d{2}$/.test(text)) return false; const [year, month, day] = text.split('-').map(Number); const date = new Date(year, month - 1, day); return date.getFullYear() === year && date.getMonth() === month - 1 && date.getDate() === day }
async function saveAttributes(): Promise<void> { if (!editing.value) return; const invalid = attributes.value.find(attribute => (attribute.is_required || hasDraftValue(attributeValues.value[attribute.id])) && !isValidDraftValue(attribute, attributeValues.value[attribute.id] ?? '')); if (invalid) { error.value = `Проверьте значение характеристики «${invalid.name}».`; return } saving.value = true; try { await saveProductAttributeValues(editing.value.id, { attributes: attributes.value.filter((attribute) => attribute.is_required || hasDraftValue(attributeValues.value[attribute.id])).map((attribute) => ({ attribute_id: attribute.id, value: valueFor(attribute) })) }) } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Не удалось сохранить характеристики.' } finally { saving.value = false } }
function selectFile(event: Event): void { selectedFile.value = (event.target as HTMLInputElement).files?.[0] ?? null }
function imageDraft(image: ProductImage): ImageForm { return imageDrafts.value[image.id] ?? { alt: image.alt ?? '' } }
async function uploadImage(): Promise<void> { if (!editing.value || !selectedFile.value) return; saving.value = true; try { const uploadedImage = await uploadProductImage(editing.value.id, selectedFile.value, { alt: imageForm.value.alt || null, sort_order: images.value.length }); selectedFile.value = null; if (imageInput.value) imageInput.value.value = ''; imageForm.value = { alt: '' }; setImages([...images.value, uploadedImage]) } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Не удалось загрузить изображение.' } finally { saving.value = false } }
async function saveImage(image: ProductImage): Promise<void> { if (!editing.value) return; saving.value = true; try { const draft = imageDraft(image); await updateProductImage(editing.value.id, image.id, { alt: draft.alt || null }); setImages(await getProductImages(editing.value.id)) } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Не удалось сохранить изображение.' } finally { saving.value = false } }
function startImageDrag(image: ProductImage): void { draggedImageId.value = image.id }
async function dropImage(targetImage: ProductImage): Promise<void> { if (!editing.value || draggedImageId.value === null || draggedImageId.value === targetImage.id) return; const previousImages = images.value; const sourceIndex = previousImages.findIndex((image) => image.id === draggedImageId.value); const targetIndex = previousImages.findIndex((image) => image.id === targetImage.id); if (sourceIndex < 0 || targetIndex < 0) return; const reorderedImages = [...previousImages]; const [draggedImage] = reorderedImages.splice(sourceIndex, 1); reorderedImages.splice(targetIndex, 0, draggedImage); const orderedImages = reorderedImages.map((image, index) => ({ ...image, sort_order: index, is_primary: index === 0 })); setImages(orderedImages); saving.value = true; try { for (const [index, image] of orderedImages.entries()) await updateProductImage(editing.value.id, image.id, { sort_order: index, is_primary: index === 0 }); setImages(await getProductImages(editing.value.id)) } catch (reason) { setImages(previousImages); error.value = reason instanceof Error ? reason.message : 'Не удалось изменить порядок изображений.' } finally { draggedImageId.value = null; saving.value = false } }
async function removeImage(image: ProductImage): Promise<void> { if (!editing.value || !confirm('Удалить изображение?')) return; saving.value = true; try { await deleteProductImage(editing.value.id, image.id); setImages(await getProductImages(editing.value.id)) } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Не удалось удалить изображение.' } finally { saving.value = false } }
function addRelation(): void { const productId = relatedProductOptions.value[0]?.value ?? ''; if (productId) relations.value.push({ related_product_id: productId, type: 'related', sort_order: String(relations.value.length) }) }
async function saveRelations(): Promise<void> { if (!editing.value) return; saving.value = true; try { await saveProductRelations(editing.value.id, { relations: relations.value.map((relation) => ({ related_product_id: Number(relation.related_product_id), type: relation.type, sort_order: Number(relation.sort_order) })) }) } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Не удалось сохранить связи.' } finally { saving.value = false } }
async function remove(): Promise<void> { if (!deleting.value) return; isDeleting.value = true; try { await deleteProduct(deleting.value.id); deleting.value = null; await load() } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Не удалось удалить товар.' } finally { isDeleting.value = false } }
onMounted(load)
</script>

<template>
  <section class="mx-auto admin-page">
    <div class="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-medium text-gray-500">Каталог</p><h1 class="mt-1 text-2xl font-bold tracking-tight text-gray-900 sm:text-3xl">Товары</h1><p class="mt-2 text-sm text-gray-500">Поиск и полное ведение карточек товаров.</p></div><button v-if="canManage" class="inline-flex items-center gap-2 rounded-lg bg-primary-500 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-primary-600" @click="open()"><Plus :size="18" />Добавить товар</button></div>
    <p v-if="error" class="mb-4 rounded-lg border border-error-200 bg-error-50 px-4 py-3 text-sm text-error-500">{{ error }}</p>
    <form class="rounded-xl border border-gray-200 bg-white p-5 shadow-card" @submit.prevent="load"><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><label class="text-sm font-medium text-gray-700 xl:col-span-2">Поиск<BaseInput v-model="filters.search" class="mt-1.5" searchable placeholder="Название, URL или SKU" /></label><label class="text-sm font-medium text-gray-700">Категория<BaseSelect v-model="filters.category_id" class="mt-1.5" :options="filterCategoryOptions" accessible-name="Категория" searchable /></label><label class="text-sm font-medium text-gray-700">Бренд<BaseSelect v-model="filters.brand_id" class="mt-1.5" :options="filterBrandOptions" accessible-name="Бренд" searchable /></label><label class="text-sm font-medium text-gray-700">Активность<BaseSelect v-model="filters.is_active" class="mt-1.5" :options="stateOptions" accessible-name="Активность" /></label><label class="text-sm font-medium text-gray-700">Остаток<BaseSelect v-model="filters.has_stock" class="mt-1.5" :options="stockOptions" accessible-name="Остаток" /></label><label class="text-sm font-medium text-gray-700">Цена от<BaseInput v-model="filters.price_from" class="mt-1.5" type="number" min="0" step="0.01" /></label><label class="text-sm font-medium text-gray-700">Цена до<BaseInput v-model="filters.price_to" class="mt-1.5" type="number" min="0" step="0.01" /></label></div><div class="mt-5 flex gap-3"><button class="inline-flex items-center gap-2 rounded-lg bg-primary-500 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60" :disabled="loading"><Search :size="18" />{{ loading ? 'Поиск…' : 'Найти' }}</button><button class="rounded-lg px-4 py-2.5 text-sm font-semibold text-gray-600 hover:bg-gray-50" type="button" @click="resetFilters">Сбросить</button></div></form>
    <p class="mt-6 text-sm text-gray-500">Найдено: {{ pagination?.total ?? 0 }}</p><div class="mt-3 overflow-hidden rounded-xl border border-gray-200 bg-white shadow-card"><div v-if="products.length" class="divide-y divide-gray-100"><article v-for="product in products" :key="product.id" class="flex items-center gap-4 p-4 sm:p-5"><span class="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-primary-50 text-primary-600"><Package :size="20" /></span><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><h2 class="truncate font-semibold text-gray-800">{{ product.name }}</h2><span class="admin-badge rounded-full px-2 py-1 text-xs font-medium" :class="product.is_active ? 'bg-success-50 text-success-500' : 'bg-gray-100 text-gray-500'">{{ product.is_active ? 'Активен' : 'Скрыт' }}</span></div><p class="mt-1 truncate text-sm text-gray-500">{{ product.category?.name }}<template v-if="product.brand"> · {{ product.brand.name }}</template> · /{{ product.slug }}</p></div><div v-if="canManage" class="flex gap-1"><button class="rounded-lg p-2 text-gray-500 hover:bg-primary-50 hover:text-primary-600" aria-label="Редактировать товар" @click="open(product)"><Pencil :size="17" /></button><button class="rounded-lg p-2 text-gray-500 hover:bg-error-50 hover:text-error-500" aria-label="Удалить товар" @click="deleting = product"><Trash2 :size="17" /></button></div></article></div><div v-else class="px-5 py-14 text-center text-sm text-gray-500">По выбранным условиям товары не найдены.</div></div>

    <PaginationControls v-if="pagination" :meta="pagination" :loading="loading" @change="load" />
    <div v-if="opened" class="fixed inset-0 z-50 bg-gray-900/50 p-3 sm:p-6" @click.self="close"><section class="mx-auto flex h-full max-w-6xl flex-col overflow-hidden rounded-xl bg-white shadow-xl"><header class="flex items-start justify-between border-b border-gray-200 px-5 py-4 sm:px-6"><div><h2 class="text-lg font-bold text-gray-900">{{ editing ? `Товар: ${editing.name}` : 'Новый товар' }}</h2><p class="mt-1 text-sm text-gray-500">Все данные товара находятся в этой карточке.</p></div><button type="button" class="rounded-lg p-1 text-gray-500 hover:bg-gray-50" aria-label="Закрыть" @click="close"><X :size="20" /></button></header><div class="border-b border-gray-200 px-5 sm:px-6"><nav class="flex overflow-x-auto"><button v-for="tab in tabs" :key="tab.id" class="shrink-0 border-b-2 px-4 py-3 text-sm font-semibold" :class="activeTab === tab.id ? 'border-primary-500 text-primary-600' : 'border-transparent text-gray-500 hover:text-gray-800'" :disabled="!editing && tab.id !== 'main'" @click="activeTab = tab.id">{{ tab.label }}</button></nav></div><div class="flex-1 overflow-y-auto p-5 sm:p-6"><p v-if="error" class="mb-4 rounded-lg border border-error-200 bg-error-50 px-4 py-3 text-sm text-error-500">{{ error }}</p>
      <form v-if="activeTab === 'main'" class="grid gap-4 sm:grid-cols-2" @submit.prevent="saveMain"><label class="text-sm font-medium text-gray-700">Название<BaseInput :model-value="form.name" class="mt-1.5" required @update:model-value="updateName" /></label><label class="text-sm font-medium text-gray-700">URL (slug)<BaseInput :model-value="form.slug" class="mt-1.5" pattern="[a-z0-9]+(-[a-z0-9]+)*" required @update:model-value="(value) => { form.slug = value; manuallyEditedSlug = true }" /></label><label class="text-sm font-medium text-gray-700">Категория<BaseSelect v-model="selectedCategory" class="mt-1.5" :options="categoryOptions" placeholder="Выберите категорию" accessible-name="Категория" searchable /></label><label class="text-sm font-medium text-gray-700">Бренд<BaseSelect v-model="selectedBrand" class="mt-1.5" :options="brandOptions" accessible-name="Бренд" searchable /></label><label class="text-sm font-medium text-gray-700 sm:col-span-2">Описание<BaseTextarea v-model="form.description" class="mt-1.5 font-normal" /></label><BaseCheckbox :checked="form.is_active" mode="boolean" class="sm:col-span-2" @update:checked="form.is_active = $event">Товар активен и доступен на витрине</BaseCheckbox><div class="sm:col-span-2 mt-2 flex justify-end"><button class="inline-flex items-center gap-2 rounded-lg bg-primary-500 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60" :disabled="saving"><Save :size="18" />{{ saving ? 'Сохранение…' : editing ? 'Сохранить изменения' : 'Сохранить и продолжить' }}</button></div></form>
      <div v-else-if="activeTab === 'variants'">
        <div class="mb-5 flex items-center justify-between"><div><h3 class="font-bold text-gray-900">Варианты, цены и остатки</h3><p class="mt-1 text-sm text-gray-500">Выберите только те характеристики, которые отличают этот SKU от основного товара.</p></div><button v-if="canManage" class="inline-flex items-center gap-2 rounded-lg bg-primary-500 px-3 py-2 text-sm font-semibold text-white" @click="openVariant()"><Plus :size="17" />Добавить</button></div>
        <form v-if="variantEditorOpen" class="mb-5 grid gap-4 rounded-xl border border-gray-200 bg-gray-25 p-4 sm:grid-cols-2" @submit.prevent="saveVariant">
          <label class="text-sm font-medium text-gray-700">Название<BaseInput v-model="variantForm.name" class="mt-1.5" required /></label><label class="text-sm font-medium text-gray-700">SKU<BaseInput v-model="variantForm.sku" class="mt-1.5" required pattern="[A-Za-z0-9][A-Za-z0-9._-]*" /></label><label class="text-sm font-medium text-gray-700">Цена<BaseInput v-model="variantForm.price" class="mt-1.5" type="number" min="0" step="0.01" required /></label><label class="text-sm font-medium text-gray-700">Старая цена<BaseInput v-model="variantForm.old_price" class="mt-1.5" type="number" min="0" step="0.01" /></label><label class="text-sm font-medium text-gray-700">Остаток<BaseInput v-model="variantForm.stock_quantity" class="mt-1.5" type="number" min="0" required /></label><label class="text-sm font-medium text-gray-700">Порядок<BaseInput v-model="variantForm.sort_order" class="mt-1.5" type="number" min="0" required /></label><BaseCheckbox :checked="variantForm.is_active" mode="boolean" @update:checked="variantForm.is_active = $event">Вариант активен</BaseCheckbox>
          <div class="sm:col-span-2 rounded-lg border border-gray-200 bg-white p-4"><div class="flex items-center justify-between"><div><p class="text-sm font-semibold text-gray-800">Различающиеся характеристики</p><p class="mt-1 text-xs text-gray-500">Можно выбрать только характеристики, назначенные категории товара.</p></div><button class="inline-flex items-center gap-1 rounded-lg px-2 py-1.5 text-sm font-semibold text-primary-600 hover:bg-primary-50 disabled:opacity-50" type="button" :disabled="variantForm.attribute_values.length >= attributes.length" @click="addVariantAttribute"><Plus :size="16" />Добавить</button></div><div v-if="variantForm.attribute_values.length" class="mt-3 space-y-3"><div v-for="(item, index) in variantForm.attribute_values" :key="index" class="grid gap-3 sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto]"><BaseSelect :model-value="item.attribute_id" :options="variantAttributeOptions(index)" placeholder="Характеристика" :accessible-name="`Характеристика варианта ${index + 1}`" searchable @update:model-value="changeVariantAttribute(index, $event)" /><AttributeValueField v-if="variantAttribute(item.attribute_id)" v-model="item.value" :attribute="variantAttribute(item.attribute_id)!" :accessible-name="`Значение характеристики ${index + 1}`" required /><button class="rounded-lg p-2 text-error-500 hover:bg-error-50" type="button" aria-label="Удалить характеристику варианта" @click="variantForm.attribute_values.splice(index, 1)"><Trash2 :size="18" /></button></div></div><p v-else class="mt-3 text-sm text-gray-500">Если SKU не отличается характеристиками, оставьте этот блок пустым.</p></div>
          <div class="flex justify-end gap-2 sm:col-span-2"><button type="button" class="rounded-lg px-3 py-2 text-sm font-semibold text-gray-600" @click="variantEditorOpen = false">Отмена</button><button class="rounded-lg bg-primary-500 px-3 py-2 text-sm font-semibold text-white">Сохранить</button></div>
        </form>
        <div v-if="variants.length" class="divide-y overflow-hidden rounded-xl border border-gray-200"><article v-for="variant in variants" :key="variant.id" class="flex flex-wrap items-center gap-3 p-4"><div class="min-w-0 flex-1"><p class="font-semibold text-gray-800">{{ variant.name }} <span class="font-normal text-gray-500">· {{ variant.sku }}</span></p><p v-if="variant.attribute_values.length" class="mt-1 text-sm text-primary-600">{{ variant.attribute_values.map((item) => `${item.attribute?.name ?? 'Характеристика'}: ${valueToInput(item.value)}`).join(' · ') }}</p><p class="mt-1 text-sm text-gray-500">{{ variant.price }} ₽ · Остаток: {{ variant.stock_quantity }}</p></div><button class="rounded-lg p-2 text-primary-600 hover:bg-primary-50" @click="openVariant(variant)"><Pencil :size="17" /></button><button class="rounded-lg p-2 text-error-500 hover:bg-error-50" @click="removeVariant(variant)"><Trash2 :size="17" /></button></article></div><p v-else class="rounded-xl border border-dashed border-gray-300 px-5 py-12 text-center text-sm text-gray-500">Вариантов пока нет.</p>
      </div>
      <form v-else-if="activeTab === 'attributes'" @submit.prevent="saveAttributes"><div class="mb-5 flex items-center justify-between"><div><h3 class="font-bold text-gray-900">Характеристики</h3><p class="mt-1 text-sm text-gray-500">Поля определяются выбранной категорией.</p></div><button class="inline-flex items-center gap-2 rounded-lg bg-primary-500 px-3 py-2 text-sm font-semibold text-white" :disabled="saving"><Save :size="17" />Сохранить</button></div><div v-if="attributes.length" class="grid gap-5 rounded-xl border border-gray-200 p-5 sm:grid-cols-2"><label v-for="attribute in attributes" :key="attribute.id" class="text-sm font-medium text-gray-700">{{ attribute.name }}<span v-if="attribute.is_required" class="ml-1 text-error-500">*</span><span v-if="attribute.unit" class="ml-1 text-gray-400">({{ attribute.unit }})</span><AttributeValueField :model-value="attributeValues[attribute.id] ?? ''" class="mt-1.5" :attribute="attribute" :accessible-name="attribute.name" :required="attribute.is_required" @update:model-value="attributeValues[attribute.id] = $event" /></label></div><p v-else class="rounded-xl border border-dashed border-gray-300 px-5 py-12 text-center text-sm text-gray-500">Для этой категории характеристики не назначены.</p></form>
      <div v-else-if="activeTab === 'images'"><div class="mb-5"><h3 class="font-bold text-gray-900">Фотографии</h3><p class="mt-1 text-sm text-gray-500">Перетащите карточки в нужном порядке — первая фотография станет обложкой. JPEG, PNG или WebP до 10 МБ.</p></div><form class="mb-6 grid gap-4 rounded-xl border border-gray-200 bg-gray-25 p-4 sm:grid-cols-2" @submit.prevent="uploadImage"><label class="text-sm font-medium text-gray-700">Файл<input ref="imageInput" class="mt-1.5 block w-full text-sm text-gray-600 file:mr-3 file:rounded-lg file:border-0 file:bg-primary-50 file:px-3 file:py-2 file:font-semibold file:text-primary-600" type="file" accept="image/jpeg,image/png,image/webp" required @change="selectFile" /></label><label class="text-sm font-medium text-gray-700">Alt-текст<BaseInput v-model="imageForm.alt" class="mt-1.5" /></label><div class="sm:col-span-2"><button class="inline-flex items-center gap-2 rounded-lg bg-primary-500 px-3 py-2 text-sm font-semibold text-white" :disabled="saving"><ImagePlus :size="17" />Загрузить изображение</button></div></form><div v-if="images.length" class="grid gap-5 sm:grid-cols-2 xl:grid-cols-3"><article v-for="(image, index) in images" :key="image.id" class="relative overflow-hidden rounded-xl border border-gray-200 transition-opacity" :class="{ 'cursor-grab opacity-50': draggedImageId === image.id }" :draggable="canManage && !saving" @dragstart="startImageDrag(image)" @dragend="draggedImageId = null" @dragover.prevent @drop="dropImage(image)"><img :src="image.url" :alt="image.alt ?? ''" class="aspect-[4/3] w-full bg-gray-50 object-cover" /><p v-if="index === 0" class="absolute left-3 top-3 z-10 inline-flex items-center gap-1 rounded-full bg-warning-50 px-2 py-1 text-xs font-semibold text-warning-600 shadow-sm"><Star :size="13" />Обложка</p><div class="p-4"><label class="block text-sm font-medium text-gray-700">Alt-текст<BaseInput v-model="imageDrafts[image.id].alt" class="mt-1.5" /></label><div class="mt-4 flex items-center justify-between"><span v-if="canManage" class="inline-flex items-center gap-1 text-sm text-gray-400" title="Перетащите карточку, чтобы изменить порядок"><GripVertical :size="18" />Перетащить</span><span v-else /><div class="flex"><button class="inline-flex items-center gap-1 rounded-lg px-2 py-2 text-sm font-semibold text-primary-600 hover:bg-primary-50" :disabled="saving" @click="saveImage(image)"><Save :size="16" />Сохранить</button><button v-if="canManage" class="inline-flex items-center gap-1 rounded-lg px-2 py-2 text-sm font-semibold text-error-500 hover:bg-error-50" :disabled="saving" @click="removeImage(image)"><Trash2 :size="16" />Удалить</button></div></div></div></article></div><p v-else class="rounded-xl border border-dashed border-gray-300 px-5 py-12 text-center text-sm text-gray-500">Фотографий пока нет.</p></div>
      <div v-else><div class="mb-5 flex items-center justify-between"><div><h3 class="font-bold text-gray-900">Связанные товары</h3><p class="mt-1 text-sm text-gray-500">Добавьте связанные или рекомендуемые позиции.</p></div><button class="inline-flex items-center gap-2 rounded-lg bg-primary-500 px-3 py-2 text-sm font-semibold text-white" :disabled="saving" @click="saveRelations"><Save :size="17" />Сохранить</button></div><div v-if="relations.length" class="space-y-3"><div v-for="(relation, index) in relations" :key="index" class="grid gap-3 rounded-xl border border-gray-200 p-4 sm:grid-cols-[minmax(0,1fr)_180px_110px_auto]"><BaseSelect v-model="relation.related_product_id" :options="relatedProductOptions" placeholder="Выберите товар" :accessible-name="`Связанный товар ${index + 1}`" searchable /><BaseSelect v-model="relation.type" :options="relationTypeOptions" accessible-name="Тип связи" /><BaseInput v-model="relation.sort_order" type="number" min="0" aria-label="Порядок" /><button class="rounded-lg p-2 text-error-500 hover:bg-error-50" type="button" aria-label="Удалить связь" @click="relations.splice(index, 1)"><Trash2 :size="18" /></button></div></div><p v-else class="rounded-xl border border-dashed border-gray-300 px-5 py-10 text-center text-sm text-gray-500">Связанных товаров пока нет.</p><button class="mt-4 inline-flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-semibold text-primary-600 hover:bg-primary-50" type="button" :disabled="!relatedProductOptions.length" @click="addRelation"><Plus :size="17" />Добавить связь</button></div>
    </div></section></div>
    <div v-if="deleting" class="fixed inset-0 z-[60] grid place-items-center bg-gray-900/50 p-4"><section class="w-full max-w-md rounded-xl bg-white p-6 shadow-xl"><h2 class="text-lg font-bold text-gray-900">Удалить товар?</h2><p class="mt-3 text-sm text-gray-500">Товар «{{ deleting.name }}» будет удалён.</p><div class="mt-6 flex justify-end gap-3"><button class="rounded-lg px-4 py-2.5 text-sm font-semibold text-gray-600" type="button" :disabled="isDeleting" @click="deleting = null">Отмена</button><button class="rounded-lg bg-error-500 px-4 py-2.5 text-sm font-semibold text-white" type="button" :disabled="isDeleting" @click="remove">{{ isDeleting ? 'Удаление…' : 'Удалить' }}</button></div></section></div>
  </section>
</template>
