<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { Boxes, Pencil, Plus, Trash2, X } from '@lucide/vue'
import BaseCheckbox from '../components/BaseCheckbox.vue'
import BaseInput from '../components/BaseInput.vue'
import BaseSelect from '../components/BaseSelect.vue'
import { getBrands, type Brand } from '../services/brands'
import { getCategories, type Category } from '../services/categories'
import { deleteProduct, getProducts, saveProduct, type Product, type ProductPayload } from '../services/products'
import { useAuthStore } from '../stores/auth'
const auth = useAuthStore(); const products = ref<Product[]>([]); const categories = ref<Category[]>([]); const brands = ref<Brand[]>([]); const error = ref(''); const opened = ref(false); const editing = ref<Product | null>(null); const deleting = ref<Product | null>(null); const isDeleting = ref(false); const manuallyEditedSlug = ref(false)
const form = ref<ProductPayload>({ category_id: 0, brand_id: null, name: '', slug: '', description: '', is_active: true })
const canManage = computed(() => auth.hasPermission('catalog.manage'))
function flatten(nodes: Category[], depth = 0): Array<Category & { depth: number }> { return nodes.flatMap((item) => [{ ...item, depth }, ...flatten(item.children ?? [], depth + 1)]) }
const categoryOptions = computed(() => flatten(categories.value).filter((item) => item.is_active).map((item) => ({ value: String(item.id), label: `${'— '.repeat(item.depth)}${item.name}` })))
const brandOptions = computed(() => [{ value: '', label: 'Без бренда' }, ...brands.value.map((item) => ({ value: String(item.id), label: item.name }))])
const selectedCategory = computed({ get: () => form.value.category_id ? String(form.value.category_id) : '', set: (value: string) => { form.value.category_id = Number(value) } })
const selectedBrand = computed({ get: () => form.value.brand_id === null ? '' : String(form.value.brand_id), set: (value: string) => { form.value.brand_id = value ? Number(value) : null } })
const transliteration: Record<string, string> = { а: 'a', б: 'b', в: 'v', г: 'g', д: 'd', е: 'e', ё: 'yo', ж: 'zh', з: 'z', и: 'i', й: 'y', к: 'k', л: 'l', м: 'm', н: 'n', о: 'o', п: 'p', р: 'r', с: 's', т: 't', у: 'u', ф: 'f', х: 'kh', ц: 'ts', ч: 'ch', ш: 'sh', щ: 'shch', ъ: '', ы: 'y', ь: '', э: 'e', ю: 'yu', я: 'ya' }
function slugify(value: string): string { return Array.from(value.toLowerCase(), (character) => transliteration[character] ?? character).join('').normalize('NFKD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') }
function updateName(value: string): void { form.value.name = value; if (!manuallyEditedSlug.value) form.value.slug = slugify(value) }
function open(product: Product | null = null): void { opened.value = false; editing.value = product; manuallyEditedSlug.value = product !== null; form.value = product ? { category_id: product.category_id, brand_id: product.brand_id, name: product.name, slug: product.slug, description: product.description ?? '', is_active: product.is_active } : { category_id: 0, brand_id: null, name: '', slug: '', description: '', is_active: true }; queueMicrotask(() => { opened.value = true }) }
async function load(): Promise<void> { try { [products.value, categories.value, brands.value] = await Promise.all([getProducts(), getCategories(), getBrands()]) } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Не удалось загрузить товары.' } }
async function save(): Promise<void> { try { await saveProduct(editing.value?.id ?? null, form.value); opened.value = false; await load() } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Не удалось сохранить товар.' } }
async function remove(): Promise<void> { if (!deleting.value) return; isDeleting.value = true; try { await deleteProduct(deleting.value.id); deleting.value = null; await load() } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Не удалось удалить товар.' } finally { isDeleting.value = false } }
onMounted(load)
</script>
<template>
  <section class="mx-auto admin-page"><div class="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-medium text-gray-500">Каталог</p><h1 class="mt-1 text-2xl font-bold tracking-tight text-gray-900 sm:text-3xl">Товары</h1></div><button v-if="canManage" class="inline-flex items-center gap-2 rounded-lg bg-primary-500 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-primary-600" @click="open()"><Plus :size="18" />Добавить товар</button></div><p v-if="error" class="mb-4 rounded-lg border border-error-200 bg-error-50 px-4 py-3 text-sm text-error-500">{{ error }}</p><div class="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-card"><div v-if="products.length" class="divide-y divide-gray-100"><article v-for="product in products" :key="product.id" class="flex items-center gap-4 p-4 sm:p-5"><span class="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-primary-50 text-primary-600"><Boxes :size="20" /></span><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><h2 class="truncate font-semibold text-gray-800">{{ product.name }}</h2><span class="admin-badge rounded-full px-2 py-1 text-xs font-medium" :class="product.is_active ? 'bg-success-50 text-success-600' : 'bg-gray-100 text-gray-500'">{{ product.is_active ? 'Активен' : 'Скрыт' }}</span></div><p class="mt-1 truncate text-sm text-gray-500">{{ product.category?.name }}<template v-if="product.brand"> · {{ product.brand.name }}</template> · /{{ product.slug }}</p></div><div v-if="canManage" class="flex gap-1"><button class="rounded-lg p-2 text-gray-500 hover:bg-primary-50 hover:text-primary-600" @click="open(product)"><Pencil :size="17" /></button><button class="rounded-lg p-2 text-gray-500 hover:bg-error-50 hover:text-error-500" @click="deleting = product"><Trash2 :size="17" /></button></div></article></div><div v-else class="px-5 py-14 text-center text-sm text-gray-500">Товаров пока нет.</div></div>
    <div v-if="opened" class="fixed inset-0 z-50 grid place-items-center bg-gray-900/50 p-4" @click.self="opened = false"><form class="admin-dialog-content w-full max-w-2xl overflow-y-auto rounded-xl bg-white p-6 shadow-xl" @submit.prevent="save"><div class="flex items-start justify-between"><div><h2 class="text-lg font-bold text-gray-900">{{ editing ? `Товар: ${editing.name}` : 'Новый товар' }}</h2><p class="mt-1 text-sm text-gray-500">Основные сведения карточки товара.</p></div><button type="button" class="rounded-lg p-1 text-gray-500" @click="opened = false"><X :size="20" /></button></div><div class="mt-6 grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium text-gray-700">Название<BaseInput :model-value="form.name" class="mt-1.5" required @update:model-value="updateName" /></label><label class="text-sm font-medium text-gray-700">Технический код<BaseInput :model-value="form.slug" class="mt-1.5" pattern="[a-z0-9]+(-[a-z0-9]+)*" required @update:model-value="(value) => { form.slug = value; manuallyEditedSlug = true }" /></label><label class="text-sm font-medium text-gray-700">Категория<BaseSelect v-model="selectedCategory" class="mt-1.5" :options="categoryOptions" placeholder="Выберите категорию" accessible-name="Категория" searchable /></label><label class="text-sm font-medium text-gray-700">Бренд<BaseSelect v-model="selectedBrand" class="mt-1.5" :options="brandOptions" accessible-name="Бренд" searchable /></label><label class="text-sm font-medium text-gray-700 sm:col-span-2">Описание<textarea v-model="form.description" class="mt-1.5 min-h-24 w-full rounded-lg border border-gray-300 p-3 font-normal outline-none focus:border-primary-500" /></label><BaseCheckbox :checked="form.is_active" mode="boolean" class="sm:col-span-2" @update:checked="form.is_active = $event">Товар активен и доступен на витрине</BaseCheckbox></div><div class="mt-6 flex justify-end gap-3"><button type="button" class="rounded-lg px-4 py-2.5 text-sm font-semibold text-gray-600" @click="opened = false">Отмена</button><button class="rounded-lg bg-primary-500 px-4 py-2.5 text-sm font-semibold text-white">Сохранить</button></div></form></div>
    <div v-if="deleting" class="fixed inset-0 z-[60] grid place-items-center bg-gray-900/50 p-4"><section class="w-full max-w-md rounded-xl bg-white p-6 shadow-xl"><h2 class="text-lg font-bold text-gray-900">Удалить товар?</h2><p class="mt-3 text-sm text-gray-500">Товар «{{ deleting.name }}» будет удалён.</p><div class="mt-6 flex justify-end gap-3"><button class="rounded-lg px-4 py-2.5 text-sm font-semibold text-gray-600" type="button" :disabled="isDeleting" @click="deleting = null">Отмена</button><button class="rounded-lg bg-error-500 px-4 py-2.5 text-sm font-semibold text-white" type="button" :disabled="isDeleting" @click="remove">{{ isDeleting ? 'Удаление…' : 'Удалить' }}</button></div></section></div>
  </section>
</template>
