import { apiFetch, requestCsrfCookie } from './auth'
import { loadAllPages, withPage, type PageRequest, type PaginatedResponse } from './pagination'

export type ProductImage = { id: number; product_id: number; url: string; mime_type: string; size: number; alt: string | null; is_primary: boolean; sort_order: number; created_at: string; updated_at: string }
export type ProductImageUpdatePayload = { alt?: string | null; is_primary?: boolean; sort_order?: number }
async function fail(response: Response): Promise<never> { const body = (await response.json().catch(() => ({}))) as { error?: { message?: string; details?: Record<string, string[]> } }; throw new Error(Object.values(body.error?.details ?? {}).flat()[0] ?? body.error?.message ?? 'Не удалось выполнить запрос.') }
export async function getProductImages(productId: number, request: PageRequest = {}): Promise<PaginatedResponse<ProductImage>> { const query = new URLSearchParams(); withPage(query, request); const response = await apiFetch(`/admin/products/${productId}/images${query.size ? `?${query}` : ''}`); if (!response.ok) return fail(response); return (await response.json()) as PaginatedResponse<ProductImage> }
export async function getAllProductImages(productId: number): Promise<ProductImage[]> { return loadAllPages((request) => getProductImages(productId, request)) }
export async function uploadProductImage(productId: number, file: File, payload: Omit<ProductImageUpdatePayload, 'alt'>): Promise<ProductImage> { await requestCsrfCookie(); const form = new FormData(); form.append('image', file); form.append('is_primary', payload.is_primary ? '1' : '0'); form.append('sort_order', String(payload.sort_order ?? 0)); const response = await apiFetch(`/admin/products/${productId}/images`, { method: 'POST', body: form }); if (!response.ok) return fail(response); return ((await response.json()) as { data: ProductImage }).data }
export async function updateProductImage(productId: number, id: number, payload: ProductImageUpdatePayload): Promise<ProductImage> { await requestCsrfCookie(); const response = await apiFetch(`/admin/products/${productId}/images/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (!response.ok) return fail(response); return ((await response.json()) as { data: ProductImage }).data }
export async function deleteProductImage(productId: number, id: number): Promise<void> { await requestCsrfCookie(); const response = await apiFetch(`/admin/products/${productId}/images/${id}`, { method: 'DELETE' }); if (!response.ok) return fail(response) }
